-- ==============================================
-- FIX USERS IN NEON DATABASE
-- Run this in Neon SQL Editor:
-- https://console.neon.tech/app/projects/spring-mountain-97978355
-- ==============================================

-- 1. Fix ALL existing users: set approval_status to APPROVED
UPDATE users
SET approval_status = 'APPROVED',
    is_approved = true,
    is_active = true
WHERE approval_status = 'PENDING' OR approval_status IS NULL;

-- 2. Delete and recreate admin user with correct password hash
-- (bcrypt hash for "admin123" generated by passlib)
DELETE FROM users WHERE phone = '9999999999';

INSERT INTO users (name, phone, email, password_hash, role, is_active, is_approved, approval_status)
VALUES (
    'System Administrator',
    '9999999999',
    'admin@jesusja.com',
    '$2b$12$aIdxp2d.YyqkR8W0GnZCb.xRpBSLJOR5fOP4FG4alb5UXL/HUg03e',
    'ADMIN',
    true,
    true,
    'APPROVED'
);

-- 3. Verify the fix
SELECT id, name, phone, role, is_active, is_approved, approval_status
FROM users
ORDER BY id;
